|Portal| 2022-09-09 02:28:48 [..] Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=64868)
|Portal| 2022-09-09 02:28:48 [..] Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=64870)
|Portal| 2022-09-09 02:28:48 [..] Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=64872)
|Portal| 2022-09-09 02:28:48 [..] Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=64874)
|Portal| 2022-09-09 02:28:48 [..] Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=64873)
|Portal| 2022-09-09 02:28:49 [..] Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=64871)
|Portal| 2022-09-09 02:30:11 [..] Portal starting server ... 
|Portal| 2022-09-09 02:32:59 [!!] Unhandled Error
	Traceback (most recent call last):
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 101, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 85, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 83, in callWithContext
	    return func(*args, **kw)
	--- <exception caught here> ---
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 576, in doConnect
	    self.failIfNotConnected(error.getConnectError((err, strerror(err))))
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 484, in failIfNotConnected
	    self.connector.connectionFailed(failure.Failure(err))
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\base.py", line 1199, in connectionFailed
	    self.factory.clientConnectionFailed(self, reason)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\proxy.py", line 115, in clientConnectionFailed
	    self.father.finish()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\server.py", line 279, in finish
	    return http.Request.finish(self)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 1131, in finish
	    raise RuntimeError(
	builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
	
|Portal| 2022-09-09 02:32:59 [!!] Unhandled Error
	Traceback (most recent call last):
	  File "C:\muddev\evenv\Lib\site-packages\twisted\application\app.py", line 306, in runReactorWithLogging
	    reactor.run()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\base.py", line 1318, in run
	    self.mainLoop()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\base.py", line 1331, in mainLoop
	    reactorBaseSelf.doIteration(t)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\selectreactor.py", line 143, in doSelect
	    _logrun(selectable, _drdw, selectable, method)
	--- <exception caught here> ---
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 101, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 85, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 83, in callWithContext
	    return func(*args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\selectreactor.py", line 154, in _doReadOrWrite
	    self._disconnectSelectable(selectable, why, method == "doRead")
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\posixbase.py", line 306, in _disconnectSelectable
	    selectable.connectionLost(failure.Failure(why))
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 505, in connectionLost
	    self.failIfNotConnected(error.ConnectError(string=reason))
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 484, in failIfNotConnected
	    self.connector.connectionFailed(failure.Failure(err))
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\base.py", line 1199, in connectionFailed
	    self.factory.clientConnectionFailed(self, reason)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\proxy.py", line 115, in clientConnectionFailed
	    self.father.finish()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\server.py", line 279, in finish
	    return http.Request.finish(self)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 1131, in finish
	    raise RuntimeError(
	builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
	
|Portal| 2022-09-09 02:33:49 [..] (TCP Port 4001 Closed)
|Portal| 2022-09-09 02:33:49 [..] (TCP Port 4002 Closed)
|Portal| 2022-09-09 02:33:49 [..] (TCP Port 4000 Closed)
|Portal| 2022-09-09 02:33:49 [..] (TCP Port 4006 Closed)
|Portal| 2022-09-09 02:33:49 [..] Main loop terminated.
|Portal| 2022-09-09 02:33:49 [..] Server Shut Down.
|Portal| 2022-09-09 02:33:49 [..] Server Shut Down.
|Portal| 2022-09-09 02:33:58 [..] Loaded.
|Portal| 2022-09-09 02:33:57 [..] Loading c:\muddev\evennia\evennia\server\portal\portal.py...
|Portal| 2022-09-09 02:33:58 [EE] Could not find file-help module world.help_entries (skipping).
|Portal| 2022-09-09 02:33:58 [..] Loaded.
|Portal| 2022-09-09 02:33:58 [..] twistd 21.7.0 (C:\muddev\evenv\Scripts\python.exe 3.9.2) starting up.
|Portal| 2022-09-09 02:33:58 [..] reactor class: twisted.internet.selectreactor.SelectReactor.
|Portal| 2022-09-09 02:33:58 [..] AMP starting on 4006
|Portal| 2022-09-09 02:33:58 [..] Telnet starting on 4000
|Portal| 2022-09-09 02:33:58 [..] Websocket starting on 4002
|Portal| 2022-09-09 02:33:58 [..] Webserver-proxy starting on 4001
|Portal| 2022-09-09 02:33:59 [..] Portal starting server ... 
|Portal| 2022-09-09 02:37:38 [..] (TCP Port 4001 Closed)
|Portal| 2022-09-09 02:37:38 [..] (TCP Port 4000 Closed)
|Portal| 2022-09-09 02:37:38 [..] (TCP Port 4006 Closed)
|Portal| 2022-09-09 02:37:38 [..] (TCP Port 4002 Closed)
|Portal| 2022-09-09 02:37:38 [..] Main loop terminated.
|Portal| 2022-09-09 02:37:38 [..] Server Shut Down.
|Portal| 2022-09-09 02:37:38 [..] Server Shut Down.
|Portal| 2022-09-09 02:39:08 [..] Loaded.
|Portal| 2022-09-09 02:39:07 [..] Loading c:\muddev\evennia\evennia\server\portal\portal.py...
|Portal| 2022-09-09 02:39:07 [EE] Could not find file-help module world.help_entries (skipping).
|Portal| 2022-09-09 02:39:08 [..] Loaded.
|Portal| 2022-09-09 02:39:08 [..] twistd 21.7.0 (C:\muddev\evenv\Scripts\python.exe 3.9.2) starting up.
|Portal| 2022-09-09 02:39:08 [..] reactor class: twisted.internet.selectreactor.SelectReactor.
|Portal| 2022-09-09 02:39:08 [..] AMP starting on 4006
|Portal| 2022-09-09 02:39:08 [..] Telnet starting on 4000
|Portal| 2022-09-09 02:39:08 [..] Websocket starting on 4002
|Portal| 2022-09-09 02:39:08 [..] Webserver-proxy starting on 4001
|Portal| 2022-09-09 02:39:08 [..] Portal starting server ... 
|Portal| 2022-09-09 02:39:12 [!!] Unhandled Error
	Traceback (most recent call last):
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 101, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 85, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 83, in callWithContext
	    return func(*args, **kw)
	--- <exception caught here> ---
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 247, in doRead
	    return self._dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 252, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\protocols\basic.py", line 554, in dataReceived
	    why = self.rawDataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 706, in rawDataReceived
	    self.handleResponseEnd()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\proxy.py", line 82, in handleResponseEnd
	    self.father.finish()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\server.py", line 279, in finish
	    return http.Request.finish(self)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 1131, in finish
	    raise RuntimeError(
	builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
	
|Portal| 2022-09-09 02:39:12 [!!] Unhandled Error
	Traceback (most recent call last):
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 101, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 85, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 83, in callWithContext
	    return func(*args, **kw)
	--- <exception caught here> ---
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 247, in doRead
	    return self._dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 252, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\protocols\basic.py", line 554, in dataReceived
	    why = self.rawDataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 706, in rawDataReceived
	    self.handleResponseEnd()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\proxy.py", line 82, in handleResponseEnd
	    self.father.finish()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\server.py", line 279, in finish
	    return http.Request.finish(self)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 1131, in finish
	    raise RuntimeError(
	builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
	
|Portal| 2022-09-09 02:41:02 [..] Portal starting server ... 
|Portal| 2022-09-09 02:41:39 [..] Portal starting server ... 
|Portal| 2022-09-09 02:43:58 [..] Portal starting server ... 
|Portal| 2022-09-09 02:45:32 [..] Portal starting server ... 
|Portal| 2022-09-09 02:48:19 [..] Portal starting server ... 
|Portal| 2022-09-09 02:52:35 [..] Portal starting server ... 
|Portal| 2022-09-09 02:53:26 [..] Portal starting server ... 
|Portal| 2022-09-09 02:54:03 [..] Portal starting server ... 
|Portal| 2022-09-09 02:54:39 [..] Portal starting server ... 
|Portal| 2022-09-09 02:55:10 [..] Portal starting server ... 
|Portal| 2022-09-09 02:55:35 [..] Portal starting server ... 
|Portal| 2022-09-09 02:57:38 [..] Portal starting server ... 
|Portal| 2022-09-09 02:59:09 [..] Portal starting server ... 
|Portal| 2022-09-09 03:00:54 [..] Portal starting server ... 
|Portal| 2022-09-09 03:01:15 [..] Portal starting server ... 
|Portal| 2022-09-09 03:03:23 [..] Portal starting server ... 
|Portal| 2022-09-09 03:03:45 [..] Portal starting server ... 
|Portal| 2022-09-09 03:05:12 [..] Portal starting server ... 
|Portal| 2022-09-09 03:12:52 [..] Portal starting server ... 
|Portal| 2022-09-09 03:13:15 [..] Portal starting server ... 
|Portal| 2022-09-09 03:13:41 [..] Portal starting server ... 
|Portal| 2022-09-09 10:39:12 [..] Portal starting server ... 
