|Portal| 2022-09-30 21:01:46 [..] Loaded.
|Portal| 2022-09-30 21:01:46 [..] Loading c:\muddev\evennia\evennia\server\portal\portal.py...
|Portal| 2022-09-30 21:01:46 [EE] Could not find file-help module world.help_entries (skipping).
|Portal| 2022-09-30 21:01:46 [..] Loaded.
|Portal| 2022-09-30 21:01:46 [..] twistd 21.7.0 (C:\muddev\evenv\Scripts\python.exe 3.9.2) starting up.
|Portal| 2022-09-30 21:01:46 [..] reactor class: twisted.internet.selectreactor.SelectReactor.
|Portal| 2022-09-30 21:01:46 [..] AMP starting on 4006
|Portal| 2022-09-30 21:01:46 [..] Telnet starting on 4000
|Portal| 2022-09-30 21:01:46 [..] Websocket starting on 4002
|Portal| 2022-09-30 21:01:46 [..] Webserver-proxy starting on 4001
|Portal| 2022-09-30 21:01:47 [..] Portal starting server ... 
|Portal| 2022-09-30 21:02:53 [..] Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=53815)
|Portal| 2022-09-30 21:02:53 [..] Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=53817)
|Portal| 2022-09-30 21:02:53 [..] Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=53821)
|Portal| 2022-09-30 21:02:53 [..] Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=53823)
|Portal| 2022-09-30 21:02:53 [..] Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=53822)
|Portal| 2022-09-30 21:02:53 [..] Timing out client: IPv4Address(type='TCP', host='127.0.0.1', port=53819)
|Portal| 2022-09-30 21:03:37 [..] (TCP Port 4001 Closed)
|Portal| 2022-09-30 21:03:37 [..] (TCP Port 4000 Closed)
|Portal| 2022-09-30 21:03:37 [..] (TCP Port 4006 Closed)
|Portal| 2022-09-30 21:03:37 [..] (TCP Port 4002 Closed)
|Portal| 2022-09-30 21:03:37 [..] Main loop terminated.
|Portal| 2022-09-30 21:03:37 [..] Server Shut Down.
|Portal| 2022-09-30 21:03:37 [..] Server Shut Down.
|Portal| 2022-09-30 21:09:40 [..] Loaded.
|Portal| 2022-09-30 21:09:39 [..] Loading c:\muddev\evennia\evennia\server\portal\portal.py...
|Portal| 2022-09-30 21:09:40 [EE] Could not find file-help module world.help_entries (skipping).
|Portal| 2022-09-30 21:09:40 [..] Loaded.
|Portal| 2022-09-30 21:09:40 [..] twistd 21.7.0 (C:\muddev\evenv\Scripts\python.exe 3.9.2) starting up.
|Portal| 2022-09-30 21:09:40 [..] reactor class: twisted.internet.selectreactor.SelectReactor.
|Portal| 2022-09-30 21:09:40 [..] AMP starting on 4006
|Portal| 2022-09-30 21:09:40 [..] Telnet starting on 4000
|Portal| 2022-09-30 21:09:40 [..] Websocket starting on 4002
|Portal| 2022-09-30 21:09:40 [..] Webserver-proxy starting on 4001
|Portal| 2022-09-30 21:09:40 [..] Portal starting server ... 
|Portal| 2022-09-30 21:10:08 [!!] Unhandled Error
	Traceback (most recent call last):
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 101, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 85, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 83, in callWithContext
	    return func(*args, **kw)
	--- <exception caught here> ---
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 247, in doRead
	    return self._dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 252, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\protocols\basic.py", line 554, in dataReceived
	    why = self.rawDataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 706, in rawDataReceived
	    self.handleResponseEnd()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\proxy.py", line 82, in handleResponseEnd
	    self.father.finish()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\server.py", line 279, in finish
	    return http.Request.finish(self)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 1131, in finish
	    raise RuntimeError(
	builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
	
|Portal| 2022-09-30 21:10:08 [!!] Unhandled Error
	Traceback (most recent call last):
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 101, in callWithLogger
	    return callWithContext({"system": lp}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\log.py", line 85, in callWithContext
	    return context.call({ILogContext: newCtx}, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\python\context.py", line 83, in callWithContext
	    return func(*args, **kw)
	--- <exception caught here> ---
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\selectreactor.py", line 149, in _doReadOrWrite
	    why = getattr(selectable, method)()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 247, in doRead
	    return self._dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\internet\tcp.py", line 252, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\protocols\basic.py", line 554, in dataReceived
	    why = self.rawDataReceived(data)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 706, in rawDataReceived
	    self.handleResponseEnd()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\proxy.py", line 82, in handleResponseEnd
	    self.father.finish()
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\server.py", line 279, in finish
	    return http.Request.finish(self)
	  File "C:\muddev\evenv\Lib\site-packages\twisted\web\http.py", line 1131, in finish
	    raise RuntimeError(
	builtins.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
	
|Portal| 2022-09-30 21:12:17 [..] Portal starting server ... 
|Portal| 2022-09-30 21:13:55 [..] Portal starting server ... 
|Portal| 2022-09-30 21:18:35 [..] Portal starting server ... 
|Portal| 2022-09-30 21:24:08 [..] Portal starting server ... 
|Portal| 2022-09-30 21:27:55 [..] Portal starting server ... 
|Portal| 2022-09-30 21:34:03 [..] Portal starting server ... 
|Portal| 2022-09-30 21:35:48 [..] Portal starting server ... 
|Portal| 2022-09-30 21:44:18 [..] Portal starting server ... 
|Portal| 2022-09-30 21:47:51 [..] Portal starting server ... 
|Portal| 2022-09-30 21:48:30 [..] Portal starting server ... 
|Portal| 2022-09-30 21:49:47 [..] Portal starting server ... 
|Portal| 2022-09-30 21:51:00 [..] Portal starting server ... 
|Portal| 2022-09-30 21:54:49 [..] Portal starting server ... 
|Portal| 2022-09-30 21:55:36 [..] Portal starting server ... 
|Portal| 2022-09-30 21:58:51 [..] Portal starting server ... 
|Portal| 2022-09-30 22:03:24 [..] Portal starting server ... 
|Portal| 2022-09-30 22:03:56 [..] Portal starting server ... 
|Portal| 2022-09-30 22:04:11 [..] Portal starting server ... 
|Portal| 2022-09-30 22:05:42 [..] Portal starting server ... 
|Portal| 2022-09-30 22:13:04 [..] Portal starting server ... 
|Portal| 2022-09-30 22:13:46 [..] Portal starting server ... 
|Portal| 2022-09-30 22:15:18 [..] Portal starting server ... 
|Portal| 2022-09-30 22:15:48 [..] Portal starting server ... 
|Portal| 2022-09-30 22:19:45 [..] Portal starting server ... 
